### ISSUE TITLE
proto and protocol

### ISSUE THREAD

**Issue by ngatti-asso** [robertdebock/ansible-role-firewall#2]
Hi Robert. I found a small issue on the role readme. You use "proto":
`
     proto: udp
`
inside the example playbook, but inside the task the variable used is "protocol". You should change one of them.

**Comment by robertdebock** [comment]
Well spotted, I'll address this one in a bit. Sorry for the late reply.

**Comment by robertdebock** [comment]
When CI passes, I'll release a new version for this and close the issue.

**Comment by ngatti-asso** [comment]
Thanks to you Robert!

**Comment by robertdebock** [comment]
A new version was released, including this fix. Thanks!
