### ISSUE TITLE
No way to remove rules?

### ISSUE THREAD

**Issue by bschonec** [robertdebock/ansible-role-firewall#3]
## Proposed feature

Ability to remove rules.  Remove all rules or remove a single rule.  Once rules are added via this role there's no way to remove the rules.

## Rationale

Firewall needs come and go.  A typo on a rule can result in the rule being permanent.

**Comment by robertdebock** [comment]
You are correct, did not think of this before. I'll try to make something that solves this issue.

**Comment by bschonec** [comment]
I've made a few changes that I'll upload to my fork.

**Comment by robertdebock** [comment]
I'll close this issue, as your request was implemented in version 3.2.0 of this role.

Please let me know if this does not work for you.
